//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrettyMachines.BlazorUI.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controls {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrettyMachines.BlazorUI.Localization.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string FooterCredit {
            get {
                return ResourceManager.GetString("FooterCredit", resourceCulture);
            }
        }
        
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        internal static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        internal static string CreateNewAction {
            get {
                return ResourceManager.GetString("CreateNewAction", resourceCulture);
            }
        }
        
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        internal static string AlgorithmCatalog {
            get {
                return ResourceManager.GetString("AlgorithmCatalog", resourceCulture);
            }
        }
        
        internal static string CatalogDescription {
            get {
                return ResourceManager.GetString("CatalogDescription", resourceCulture);
            }
        }
        
        internal static string EditAsDraft {
            get {
                return ResourceManager.GetString("EditAsDraft", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        internal static string AlgorithmNotFound {
            get {
                return ResourceManager.GetString("AlgorithmNotFound", resourceCulture);
            }
        }
        
        internal static string BackToCatalog {
            get {
                return ResourceManager.GetString("BackToCatalog", resourceCulture);
            }
        }
        
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        internal static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }
        
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string MaxSteps {
            get {
                return ResourceManager.GetString("MaxSteps", resourceCulture);
            }
        }
        
        internal static string RunningStep {
            get {
                return ResourceManager.GetString("RunningStep", resourceCulture);
            }
        }
        
        internal static string FinishedAfterStepSingular {
            get {
                return ResourceManager.GetString("FinishedAfterStepSingular", resourceCulture);
            }
        }
        
        internal static string FinishedAfterStepPlural {
            get {
                return ResourceManager.GetString("FinishedAfterStepPlural", resourceCulture);
            }
        }
        
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        internal static string TapeHeadHint {
            get {
                return ResourceManager.GetString("TapeHeadHint", resourceCulture);
            }
        }
        
        internal static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        internal static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        internal static string NoStructuredDefinition {
            get {
                return ResourceManager.GetString("NoStructuredDefinition", resourceCulture);
            }
        }
        
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        internal static string ErrorHappened {
            get {
                return ResourceManager.GetString("ErrorHappened", resourceCulture);
            }
        }
        
        internal static string ErrorHappenedDetails {
            get {
                return ResourceManager.GetString("ErrorHappenedDetails", resourceCulture);
            }
        }
        
        internal static string Unhandled {
            get {
                return ResourceManager.GetString("Unhandled", resourceCulture);
            }
        }
        
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        internal static string ReloadPage {
            get {
                return ResourceManager.GetString("ReloadPage", resourceCulture);
            }
        }
        
        internal static string ReadOnlyView {
            get {
                return ResourceManager.GetString("ReadOnlyView", resourceCulture);
            }
        }
        
        internal static string BlankSymbol {
            get {
                return ResourceManager.GetString("BlankSymbol", resourceCulture);
            }
        }
        
        internal static string StrictAlphabet {
            get {
                return ResourceManager.GetString("StrictAlphabet", resourceCulture);
            }
        }
        
        internal static string NonePlaceholder {
            get {
                return ResourceManager.GetString("NonePlaceholder", resourceCulture);
            }
        }
        
        internal static string AnyPlaceholder {
            get {
                return ResourceManager.GetString("AnyPlaceholder", resourceCulture);
            }
        }
        
        internal static string NewPlaceholder {
            get {
                return ResourceManager.GetString("NewPlaceholder", resourceCulture);
            }
        }
        
        internal static string AddSymbol {
            get {
                return ResourceManager.GetString("AddSymbol", resourceCulture);
            }
        }
        
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        internal static string Initial {
            get {
                return ResourceManager.GetString("Initial", resourceCulture);
            }
        }
        
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        internal static string AddState {
            get {
                return ResourceManager.GetString("AddState", resourceCulture);
            }
        }
        
        internal static string Transitions {
            get {
                return ResourceManager.GetString("Transitions", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        internal static string Halt {
            get {
                return ResourceManager.GetString("Halt", resourceCulture);
            }
        }
        
        internal static string AddTransition {
            get {
                return ResourceManager.GetString("AddTransition", resourceCulture);
            }
        }
        
        internal static string Markers {
            get {
                return ResourceManager.GetString("Markers", resourceCulture);
            }
        }
        
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        internal static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        internal static string DuplicatePatterns {
            get {
                return ResourceManager.GetString("DuplicatePatterns", resourceCulture);
            }
        }
        
        internal static string Exact {
            get {
                return ResourceManager.GetString("Exact", resourceCulture);
            }
        }
        
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        internal static string NewTuringMachine {
            get {
                return ResourceManager.GetString("NewTuringMachine", resourceCulture);
            }
        }
        
        internal static string NewMarkovAlgorithm {
            get {
                return ResourceManager.GetString("NewMarkovAlgorithm", resourceCulture);
            }
        }
        
        internal static string StartState {
            get {
                return ResourceManager.GetString("StartState", resourceCulture);
            }
        }
        
        internal static string DoneState {
            get {
                return ResourceManager.GetString("DoneState", resourceCulture);
            }
        }
        
        internal static string StartHereComment {
            get {
                return ResourceManager.GetString("StartHereComment", resourceCulture);
            }
        }
    }
}
