//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrettyMachines.BlazorUI.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Names {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrettyMachines.BlazorUI.Localization.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MarkovAlgorithm {
            get {
                return ResourceManager.GetString("MarkovAlgorithm", resourceCulture);
            }
        }
        
        internal static string TuringMachine {
            get {
                return ResourceManager.GetString("TuringMachine", resourceCulture);
            }
        }
        
        internal static string FSM {
            get {
                return ResourceManager.GetString("FSM", resourceCulture);
            }
        }
        
        internal static string BinaryAddition {
            get {
                return ResourceManager.GetString("BinaryAddition", resourceCulture);
            }
        }
        
        internal static string BinaryIncrement {
            get {
                return ResourceManager.GetString("BinaryIncrement", resourceCulture);
            }
        }
        
        internal static string BinaryDecrement {
            get {
                return ResourceManager.GetString("BinaryDecrement", resourceCulture);
            }
        }
        
        internal static string BinarySubtraction {
            get {
                return ResourceManager.GetString("BinarySubtraction", resourceCulture);
            }
        }
        
        internal static string BinaryToDecimalConverter {
            get {
                return ResourceManager.GetString("BinaryToDecimalConverter", resourceCulture);
            }
        }
        
        internal static string DecimalToBinaryConverter {
            get {
                return ResourceManager.GetString("DecimalToBinaryConverter", resourceCulture);
            }
        }
        
        internal static string BinaryToUnaryConverter {
            get {
                return ResourceManager.GetString("BinaryToUnaryConverter", resourceCulture);
            }
        }
        
        internal static string UnaryToBinaryConverter {
            get {
                return ResourceManager.GetString("UnaryToBinaryConverter", resourceCulture);
            }
        }
        
        internal static string BracketsGrammar {
            get {
                return ResourceManager.GetString("BracketsGrammar", resourceCulture);
            }
        }
        
        internal static string UnaryToTernaryConverter {
            get {
                return ResourceManager.GetString("UnaryToTernaryConverter", resourceCulture);
            }
        }
        
        internal static string TernaryToUnaryConverter {
            get {
                return ResourceManager.GetString("TernaryToUnaryConverter", resourceCulture);
            }
        }
        
        internal static string StringReversal {
            get {
                return ResourceManager.GetString("StringReversal", resourceCulture);
            }
        }
        
        internal static string StringConcatenation {
            get {
                return ResourceManager.GetString("StringConcatenation", resourceCulture);
            }
        }
    }
}
